version: '2'
services:
  web:
    restart: always
    build: .
    volumes:
      - /code/static
    command: /bin/bash -c "python manage.py collectstatic --noinput && /usr/local/bin/gunicorn protoBase.wsgi:application -w 2 -b :8000"
  nginx:
    restart: always
    build: nginx
    command: /bin/bash -c "nginx"
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
